### ISSUE TITLE
add a code of conduct

### ISSUE THREAD

**Issue by handsomematt** [dajoh/wire#1]
potential contributors need to know if they're a cis they're not allowed to contribute

**Comment by Spanfile** [comment]
:+1:

**Comment by bonnywong** [comment]
retard

**Comment by handsomematt** [comment]
reported to github support you're in trouble now bonny wong, OPEN YOUR EYES

**Comment by bonnywong** [comment]
gitboy

**Comment by HandsomeMatt** [comment]
cis scum
